// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ButtonRepo: typeof import('./src/components/ButtonRepo.vue')['default']
    Disclosure: typeof import('@headlessui/vue')['Disclosure']
    DisclosureButton: typeof import('@headlessui/vue')['DisclosureButton']
    DisclosurePanel: typeof import('@headlessui/vue')['DisclosurePanel']
    FAQ: typeof import('./src/components/FAQ.vue')['default']
    FAQItem: typeof import('./src/components/FAQ-item.vue')['default']
    FlippedImage: typeof import('./src/components/FlippedImage.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FooterItem: typeof import('./src/components/FooterItem.vue')['default']
    Gradient: typeof import('./src/components/Gradient.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    MultiImageCard: typeof import('./src/components/MultiImageCard.vue')['default']
    MultiImageSlider: typeof import('./src/components/MultiImageSlider.vue')['default']
    NewHeader: typeof import('./src/components/NewHeader.vue')['default']
    NewSubHeader: typeof import('./src/components/NewSubHeader.vue')['default']
    PlusToClose: typeof import('./src/components/PlusToClose.vue')['default']
    Progress: typeof import('./src/components/Progress.vue')['default']
    Review: typeof import('./src/components/Review.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubHeader: typeof import('./src/components/SubHeader.vue')['default']
  }
}
